version: '3.7'

services:
  db:
    image: mysql:8
    container_name: db.template
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p", "toor"]
      timeout: 1s
      retries: 10